export default [
    {
        key:'HOTEL_MANGE',
        name:'酒店管理',
        path:'/hotel',
        order:2,
        role:'1,2'
    },
    {
        key:'HOTEL_MANGE',
        name:'机票管理',
        path:'/filght',
        order:1,
        role:'1,2'
    },
    {
        key:'HOTEL_MANGE',
        name:'路线查看',
        path:'/road',
        order:3,
        role:'2'
    },
    {
        key:'HOTEL_MANGE',
        name:'用户管理',
        path:'/users',
        order:3,
        role:'1'
    },
]